language: objective-c
osx_image: xcode7
before_install:
    - export LANG=en_US.UTF-8
    - rake install
script:
    - rake clean:example
    - rake test
    - rake analyze
notifications:
    email:
        recipients:
         - john.watson@raizlabs.com
        on_success: change
        on_failure: always
