language: objective-c
before_install: 
    - rake install
    - cd Example && pod install && cd $TRAVIS_BUILD_DIR
script: rake test
notifications:
    email:
        recipients:
         - nick.donaldson@raizlabs.com
        on_success: change
        on_failure: always
