language: objective-c
before_install: 
    - rake install
    - cd Example && pod install && cd $TRAVIS_BUILD_DIR
before_script:
    - export LANG=en_US.UTF-8
script: 
    - rake test
notifications:
    email:
        recipients:
         - nick.donaldson@raizlabs.com
        on_success: change
        on_failure: always
